//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salsa_pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaVote
    {
        public int IdeaVote_Id { get; set; }
        public Nullable<bool> IsLike { get; set; }
        public Nullable<int> Idea_Id { get; set; }
    
        public virtual Idea Idea { get; set; }
    }
}
