//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salsa_pro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Salsa6Entities : DbContext
    {
        public Salsa6Entities()
            : base("name=Salsa6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<IdeaVote> IdeaVotes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<getComment_Result> getComment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComment_Result>("getComment");
        }
    
        public virtual ObjectResult<getIdeas_Result> getIdeas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getIdeas_Result>("getIdeas");
        }
    
        public virtual ObjectResult<getStaff_Result> getStaff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getStaff_Result>("getStaff");
        }
    
        public virtual ObjectResult<Nullable<int>> getVoteThumbsDown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getVoteThumbsDown");
        }
    
        public virtual ObjectResult<Nullable<int>> getVoteThumbsUp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getVoteThumbsUp");
        }
    }
}
