//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salsa_pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Idea()
        {
            this.Comments = new HashSet<Comment>();
            this.IdeaVotes = new HashSet<IdeaVote>();
        }
    
        public int Idea_Id { get; set; }
        public Nullable<int> Tag_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string TitleOfIdea { get; set; }
        public string IdeaDetail { get; set; }
        public Nullable<System.DateTime> IdeaDate { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaVote> IdeaVotes { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
